service: react-kimhojun
runtime: nodejs20
instance_class: F1
env_variables:
  PORT: 5173
  NODE_ENV: production

handlers:
  # index.html 제공
  - url: /
    static_files: dist/index.html
    upload: dist/index.html

  # 정적 파일 제공 (assets 폴더 내 모든 파일)
  - url: /assets
    static_dir: dist/assets

  # 나머지 모든 요청을 index.html로 라우팅 (React 라우팅 처리)
  - url: /.*
    static_files: dist/index.html
    upload: dist/index.html
